kind: Deployment
apiVersion: apps/v1
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 1
  template:
    metadata:
      name: goserver
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: "aatanes/hello-go:v5.4"
          readinessProbe: # Verifica se a aplicação está de pé
            httpGet:
              path: /healthz
              port: 8000 # Aqui devemos colocar a porta do container e não do service
            periodSeconds: 3 # A cada 3 segundos ele vai fazer a verificação
            failureThreshold: 1 # Números de falhas que devem disparar o aviso
            initialDelaySeconds: 10 # Tempo de espera antes de iniciar a verificação
                                    # utilizado quando você sabe que a sua aplicação demora
                                    # um certo tempo para subir e ficar pronta
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          volumeMounts:
            - mountPath: "/app/myfamily"
              name: config
      volumes:
        - name: config   
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"