kind: Deployment
apiVersion: apps/v1
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 2
  template:
    metadata:
      name: goserver
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: "aatanes/hello-go:v3"
          envFrom:
            - configMapRef:
                name: goserver-env
          # O metodo acima pega todas as variaveis do configMap e
          # coloca todas elas como variaveis de ambiente
          # O metodo abaixo pega variavel por variavel do configMap
          # env:
          #   - name: NAME 
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: NAME
          #   - name: AGE 
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: AGE