kind: Deployment
apiVersion: apps/v1
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 1
  template:
    metadata:
      name: goserver
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: "aatanes/hello-go:v5.3"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000 # Aqui devemos colocar a porta do container e não do service
            periodSeconds: 5 # A cada 5 segundos ele vai fazer a verificação
            failureThreshold: 3 # Números de falhas que devem disparar o aviso
            timeoutSeconds: 1 # Tempo de espera, em segundos, aceitável para recebimento das respostas
            successThreshold: 1 # Numero de ok's para garantir que a aplicação está ok
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          volumeMounts:
            - mountPath: "/app/myfamily"
              name: config
      volumes:
        - name: config   
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"