kind: Deployment
apiVersion: apps/v1
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 2
  template:
    metadata:
      name: goserver
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: "aatanes/hello-go:v4"
          envFrom:
            - configMapRef:
                name: goserver-env
          volumeMounts:
            - mountPath: "/myfamily"
              name: config
      volumes:
        - name: config   
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"