apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: "goserver"
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080 
    protocol: TCP
    nodePort: 30001

# O NodePort é a forma mais arcaica de acesso e hoje é pouco utilizado
# O NodePort gera uma porta e libera essa porta em todos os nodes do seu cluster
# A porta deve estar entre os números 30000 e 32767
# Exemplo: colocando a porta 30001 no meu service

# Node 1: 30001
# Node 2: 30001
# Node 3: 30001
# Node 4: 30001