apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: "goserver"
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000 
    protocol: TCP

# - port: 80 -> Porta de acesso ao SERVICE
#    targetPort: 8080  -> Redireciona o trafégo para porta 8080 onde o CONTAINER esta esperando acesso
    

# kubectl port-forward svc/goserver-service 8080:80
# O que chegar na porta 8080 da máquina redireciona para a porta 80 do service

# Comando par acessar a API do Kubernets
# kubectl proxy --port=8000