apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: "goserver"
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080 
    protocol: TCP

# O LoadBalancer gera um IP externo para acesso ao seu cluster
# O LoadBalancer já gera um NodePort para os nodes do seu cluster
# Vamos usar esse tipo de service para expor um serviço na Internet